### ISSUE TITLE
Running in Colab

### ISSUE THREAD

**Issue by alienatorZ** [ogmacorp/PyAOgmaNeo#1]
I attempted to run this in Colab and received the following error:

ERROR: Could not build wheels for pyaogmaneo which use PEP 517 and cannot be installed directly

I could not find a workaround. Is there one available?

Thanks!

**Comment by 222464** [comment]
Hi,

Sorry I only see this issue now for some reason!

To install it on Colab, you would need to do so like this:

`pip install pyaogmaneo --no-binary :all:`

The reason it doesn't work the normal way is because Colab uses an older version of Python (3.6?) than what the pyaogmaneo binaries were compiled with.

**However**, I don't know whether or not this command will actually complete successfully - it seems Colab doesn't have cmake, so it tries to build cmake from source or something (it's hard to tell). This makes it take forever to build. For now, I do not recommend using PyAOgmaNeo with Colab (it doesn't benefit from Colab's GPUs anyway).
